spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mazhq?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: 123456
  jpa:
    properties:
      hibernate:
#        hbm2ddl:
#          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
database0:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/mazhq?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  username: root
  password: 123456
  databaseName: mazhq

database1:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/liugh?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  username: root
  password: 123456
  databaseName: liugh
